Web1Project/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Web1Project.Models;

namespace Web1Project.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult Index()
        {
            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }

            Korisnik korisnik = new Korisnik();
            if ((Korisnik)Session["PrijavljeniKorisnik"] != null)
            {
                korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            }
            ViewBag.korisnik = korisnik;

            return View();
        }

        [HttpPost]
        public JsonResult CheckUserAvailability(string userdata)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();

            if (korisnici.ContainsKey(userdata))
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult EmailValidation(string email)
        {
            bool isEmail = Regex.IsMatch(email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

            if (isEmail)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        [HttpPost]
        public ActionResult Add(Korisnik korisnik)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();

            if (korisnik.KorisnickoIme == null || korisnik.KorisnickoIme == "" || korisnik.Ime == null || korisnik.Ime == "" || korisnik.Prezime == null || korisnik.Prezime == "" || korisnik.Lozinka == null || korisnik.Lozinka == "" || korisnik.Email == null || korisnik.Email == "" || korisnik.DatumRodjenja > DateTime.Now)
            {
                Session["AlertMessage"] = "Sva polja moraju biti popunjena";
                return RedirectToAction("Index");
            }

            if (korisnici.ContainsKey(korisnik.KorisnickoIme))
            {
                Session["AlertMessage"] = "Korisnicko ime je zauzeto";
                return RedirectToAction("Index");
            }

            bool isEmail = Regex.IsMatch(korisnik.Email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

            if (isEmail)
            {
                korisnik.Id = korisnici.Count;
                korisnik.PosecujeGrupneTreninge = new List<GrupniTrening>();

                korisnik.Lozinka = Operations.hashPassword(korisnik.Lozinka);

                Write.PosetilacToDataBase(korisnik);

                Session["AlertMessage"] = "Korisnik uspesno registrovan!";                
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Session["AlertMessage"] = "Email nije validan";
                return RedirectToAction("Index");
            }
        }
    }
}

Web1Project/Controllers/VlasnikUlogovanController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Xml;
using Web1Project.Models;

namespace Web1Project.Controllers
{
    public class VlasnikUlogovanController : Controller
    {
        // GET: VlasnikUlogovan 
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult MojiFitnesCentri()
        {
            Korisnik vlasnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (vlasnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }else if (vlasnik.Uloga != Uloga.VLASNIK)
            {
                return RedirectToAction("Index", "Home");
            }


            if (!vlasnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            Dictionary<int, FitnesCentar> fitnescentri = Load.FitnesCentriFromDataBase();

            List<FitnesCentar> sortiranaLista = new List<FitnesCentar>();

            foreach (var item in fitnescentri)
            {
                if(vlasnik.Id == item.Value.Vlasnik.Id)
                {
                    sortiranaLista.Add(item.Value);
                }
            }

            sortiranaLista = sortiranaLista.OrderBy(l => l.Naziv).ToList();


            ViewBag.sortiranaLista = sortiranaLista;
            ViewBag.korisnik = vlasnik;
            ViewBag.vlasnik = vlasnik;
            ViewBag.AlertMessage = "";

            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }
            else
            {
                ViewBag.AlertMessage = null;
            }
            return View();
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult DodajFitnesCentar()
        {
            Korisnik vlasnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (vlasnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            else if (vlasnik.Uloga != Uloga.VLASNIK)
            {
                return RedirectToAction("Index", "Home");
            }


            if (!vlasnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }
            else
            {
                ViewBag.AlertMessage = null;
            }
            ViewBag.korisnik = vlasnik;

            return View();
        }

        [HttpPost]
        public ActionResult FitnesCentarDodat(string naziv, string adresa)
        {
            Dictionary<int, FitnesCentar> fitnescentriObrisani = Load.FitnesCentriFromDataBaseObrisani();

            string godinaotvaranjaS = Request["godinaotvaranja"] != null ? Request["godinaotvaranja"] : string.Empty;
            int.TryParse(godinaotvaranjaS, out int godinaotvaranja);

            string cenamesecneclanarineS = Request["cenamesecneclanarine"] != null ? Request["cenamesecneclanarine"] : string.Empty;
            int.TryParse(cenamesecneclanarineS, out int cenamesecneclanarine);

            string cenagodisnjeclanarineS = Request["cenagodisnjeclanarine"] != null ? Request["cenagodisnjeclanarine"] : string.Empty;
            int.TryParse(cenagodisnjeclanarineS, out int cenagodisnjeclanarine);

            string cenajednogtreningaS = Request["cenajednogtreninga"] != null ? Request["cenajednogtreninga"] : string.Empty;
            int.TryParse(cenajednogtreningaS, out int cenajednogtreninga);

            string cenajednoggrupnogS = Request["cenajednoggrupnog"] != null ? Request["cenajednoggrupnog"] : string.Empty;
            int.TryParse(cenajednoggrupnogS, out int cenajednoggrupnog);

            string cenajednogptS = Request["cenajednogpt"] != null ? Request["cenajednogpt"] : string.Empty;
            int.TryParse(cenajednogptS, out int cenajednogpt);

            Dictionary<int, FitnesCentar> fitnescentri = Load.FitnesCentriFromDataBase();
            bool postoji = false;
            foreach(var i in fitnescentri)
            {
                if(i.Value.Naziv.ToLower() == naziv.ToLower())
                {
                    postoji = true;
                    break;
                }
            }

            if(!postoji && naziv != "" && adresa != ""  && godinaotvaranja != 0 && cenamesecneclanarine != 0 && cenagodisnjeclanarine != 0 && cenajednogtreninga != 0 && cenajednoggrupnog != 0 && cenajednogpt != 0)
            {
                Korisnik vlasnik = (Korisnik)Session["PrijavljeniKorisnik"];

                FitnesCentar noviFitnesCentar = new FitnesCentar(vlasnik);

                noviFitnesCentar.Id = fitnescentriObrisani.Count;
                noviFitnesCentar.Naziv = naziv;
                noviFitnesCentar.Adresa = adresa;
                noviFitnesCentar.GodinaOtvaranja = godinaotvaranja;
                noviFitnesCentar.CenaMesecneClanarine = cenamesecneclanarine;
                noviFitnesCentar.CenaGodisnjeClanarine = cenagodisnjeclanarine;
                noviFitnesCentar.CenaJednogTreninga = cenajednogtreninga;
                noviFitnesCentar.CenaJednogGrupnog = cenajednoggrupnog;
                noviFitnesCentar.CenaJednogPT = cenajednogpt;

                vlasnik.FitnesCentriPoseduje.Add(noviFitnesCentar);

                Write.FitnesCentarToDataBase(noviFitnesCentar);

                // Dodaje sebi FitnesCentar u vlasnistvo
                XmlDocument xmlDoc = new XmlDocument();
                string path = Path.Combine(HostingEnvironment.MapPath("~/App_Data/korisnici.xml"));
                xmlDoc.Load(path);
                XmlNodeList nodeList = xmlDoc.DocumentElement.SelectNodes($"/Korisnici/Korisnik");

                foreach (XmlNode node in nodeList)
                {
                    if (node.SelectSingleNode("Id").InnerText == vlasnik.Id.ToString())
                    {
                        XmlNode root = node.SelectSingleNode("FitnesCentri");
                        XmlElement element = xmlDoc.CreateElement("FitnesCentar");
                        element.InnerText = noviFitnesCentar.Id.ToString();
                        root.AppendChild(element);
                    }
                }
                xmlDoc.Save(path);

                Session["AlertMessage"] = "Fitnes centar uspesno dodat!";
                return RedirectToAction("MojiFitnesCentri");
            }

            Session["AlertMessage"] = "Sva polja moraju biti pravilno popunjena";
            return RedirectToAction("DodajFitnesCentar");
        }
              
        [HttpPost]
        public ActionResult Izmeni(int id)
        { 
            Session["id"] = id;
            return RedirectToAction("IzmeniFitnesCentar");
        }
        
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult IzmeniFitnesCentar()
        {
            Korisnik vlasnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (vlasnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            else if (vlasnik.Uloga != Uloga.VLASNIK)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!vlasnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            int id = (int)Session["id"];
            Dictionary<int, FitnesCentar> fitnescentri = Load.FitnesCentriFromDataBase();

            ViewBag.korisnik = vlasnik;

            ViewBag.fitnescentar = fitnescentri[id];
            return View();
        }

        [HttpPost]
        public ActionResult FitnesCentarIzmenjen(int id, string novinaziv, string novaadresa)
        {
            Dictionary<int, FitnesCentar> fitnescentri = Load.FitnesCentriFromDataBase();       
            
            string novacenamesecneclanarineString = Request["novacenamesecneclanarine"] != null ? Request["novacenamesecneclanarine"] : string.Empty;
            string novacenagodisnjeclanarineString = Request["novacenagodisnjeclanarine"] != null ? Request["novacenagodisnjeclanarine"] : string.Empty;
            string novacenajednogtreningaString = Request["novacenajednogtreninga"] != null ? Request["novacenajednogtreninga"] : string.Empty;
            string novacenajednoggrupnogString = Request["novacenajednoggrupnog"] != null ? Request["novacenajednoggrupnog"] : string.Empty;
            string novacenajednogptString = Request["novacenajednogpt"] != null ? Request["novacenajednogpt"] : string.Empty;

            bool flag = false;

            if(novinaziv != "" || novaadresa != "" || novacenamesecneclanarineString != "" || novacenagodisnjeclanarineString != "" || novacenajednogtreningaString != "" || novacenajednoggrupnogString != "" || novacenajednogptString != "")
            {
                XmlDocument xmlDoc = new XmlDocument();
                string path = Path.Combine(HostingEnvironment.MapPath("~/App_Data/fitnescentri.xml"));
                xmlDoc.Load(path);
                XmlNodeList nodeList = xmlDoc.DocumentElement.SelectNodes($"/FitnesCentri/FitnesCentar");

                FitnesCentar fitnescentar = fitnescentri[id];

                if(novinaziv != "" && novinaziv != fitnescentar.Naziv)
                {
                    foreach(var v in fitnescentri)
                    {
                        if(v.Value.Naziv == novinaziv)
                        {
                            Session["AlertMessage"] = "Fitnes centar sa ovim nazivom vec postoji!";
                            return RedirectToAction("MojiFitnesCentri");

Web1Project/Views/VlasnikUlogovan/DodajFitnesCentar.cshtml
@{
    ViewBag.Title = "DodajFitnesCentar";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodaj fitnes centar</title>

    <script>

        var naziv = true;

        function UserCheck() {
            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#Naziv").css("border-color", "Red");
            } else {
                $.post("@Url.Action("CheckUserAvailability", "VlasnikUlogovan")",
                {
                    userdata: $("#Naziv").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#Naziv").css("border-color", "GreenYellow");
                        $("#Status1").html('');
                        naziv = true;
                    } else {
                        $("#Naziv").css("border-color", "Red");
                        $("#Status1").html('<font color="Red">Fitnes centar sa istim nazivom vec postoji!</font>');
                        naziv = false;
                    }
                });
            }
        }

        function AdresaEmpty() {
            if ($("#Adresa").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#Adresa").css("border-color", "Red");
            } else {
                $("#Status2").html('');
                $("#Adresa").css("border-color", "lightgray");
            }
        }

        function GodinaOtvaranjaEmpty() {
            if ($("#GodinaOtvaranja").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#GodinaOtvaranja").css("border-color", "Red");
            } else {
                $("#Status3").html('');
                $("#GodinaOtvaranja").css("border-color", "lightgray");
            }
        }

        function CenaMesecneClanarineEmpty() {
            if ($("#CenaMesecneClanarine").val() == "") {
                $("#Status4").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#CenaMesecneClanarine").css("border-color", "Red");
            } else {
                $("#Status4").html('');
                $("#CenaMesecneClanarine").css("border-color", "lightgray");
            }
        }

        function CenaGodisnjeClanarineEmpty() {
            if ($("#CenaGodisnjeClanarine").val() == "") {
                $("#Status5").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#CenaGodisnjeClanarine").css("border-color", "Red");
            } else {
                $("#Status5").html('');
                $("#CenaGodisnjeClanarine").css("border-color", "lightgray");
            }
        }

        function CenaJednogTreningaEmpty() {
            if ($("#CenaJednogTreninga").val() == "") {
                $("#Status6").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#CenaJednogTreninga").css("border-color", "Red");
            } else {
                $("#Status6").html('');
                $("#CenaJednogTreninga").css("border-color", "lightgray");
            }
        }

        function CenaJednogGrupnogEmpty() {
            if ($("#CenaJednogGrupnog").val() == "") {
                $("#Status7").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#CenaJednogGrupnog").css("border-color", "Red");
            } else {
                $("#Status7").html('');
                $("#CenaJednogGrupnog").css("border-color", "lightgray");
            }
        }

        function CenaJednogPTEmpty() {
            if ($("#CenaJednogPT").val() == "") {
                $("#Status8").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#CenaJednogPT").css("border-color", "Red");
            } else {
                $("#Status8").html('');
                $("#CenaJednogPT").css("border-color", "lightgray");
            }
        }

        function validateForm() {

            var dobro = true;

            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Naziv").css("border-color", "Red");
                dobro = false;
            }else if(naziv) {
                $("#Status1").html('');
                $("#Naziv").css("border-color", "GreenYellow");
            }
            if ($("#Adresa").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Adresa").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status2").html('');
                $("#Adresa").css("border-color", "lightgray");
            }
            if ($("#GodinaOtvaranja").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#GodinaOtvaranja").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status3").html('');
                $("#GodinaOtvaranja").css("border-color", "lightgray");
            }
            if ($("#CenaMesecneClanarine").val() == "") {
                $("#Status4").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#CenaMesecneClanarine").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status4").html('');
                $("#CenaMesecneClanarine").css("border-color", "lightgray");
            }
            if ($("#CenaGodisnjeClanarine").val() == "") {
                $("#Status5").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#CenaGodisnjeClanarine").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status5").html('');
                $("#CenaGodisnjeClanarine").css("border-color", "lightgray");
            }
            if ($("#CenaJednogTreninga").val() == "") {
                $("#Status6").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#CenaJednogTreninga").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status6").html('');
                $("#CenaJednogTreninga").css("border-color", "lightgray");
            }
            if ($("#CenaJednogGrupnog").val() == "") {
                $("#Status7").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#CenaJednogGrupnog").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status7").html('');
                $("#CenaJednogGrupnog").css("border-color", "lightgray");
            }
            if ($("#CenaJednogPT").val() == "") {
                $("#Status8").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#CenaJednogPT").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status8").html('');
                $("#CenaJednogPT").css("border-color", "lightgray");
            }

            return (dobro && naziv);
        }

    </script>

    <style>
        p.tekstic {
            color: grey;
        }
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
</head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.AlertMessage");
                };
            </script>
        }
        <h2 class="text-info">Dodaj novi fitnes centar</h2>
        <form method="post" action="~/VlasnikUlogovan/FitnesCentarDodat" onsubmit="return validateForm()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Naziv:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite naziv fitnes centra" maxlength="30" type="text" id="Naziv" name="naziv" onchange="UserCheck()" />
                    </div>
                    <label id="Status1" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Adresa:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite adresu fitnes centra" maxlength="70" onchange="AdresaEmpty()" id="Adresa" type="text" name="adresa" />
                    </div>
                    <label id="Status2" class="control-label col-sm-4"></label>
                </div>
                <div class="row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-4">
                        <p class="tekstic"><i>U formatu adresa i broj, grad, postanski broj</i></p>
                    </div>

                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Godina otvaranja:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite godinu otvaranja fitnes centra" onchange="GodinaOtvaranjaEmpty()" id="GodinaOtvaranja" type="number" min="1950" max="2023" step="1" name="godinaotvaranja" />
                    </div>
                    <label id="Status3" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Cena mesecne clanarine:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite cenu mesecne clanarine" onchange="CenaMesecneClanarineEmpty()" id="CenaMesecneClanarine" type="number" min="10" max="1000000" name="cenamesecneclanarine" />
                    </div>
                    <label id="Status4" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Cena godisnje clanarine:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite cenu godisnje clanarine" onchange="CenaGodisnjeClanarineEmpty()" max="1000000" id="CenaGodisnjeClanarine" type="number" min="10" name="cenagodisnjeclanarine" />
                    </div>
                    <label id="Status5" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Cena jednog treninga:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite cenu jednog treninga" onchange="CenaJednogTreningaEmpty()" max="1000000" id="CenaJednogTreninga" type="number" min="10" name="cenajednogtreninga" />
                    </div>
                    <label id="Status6" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Cena jednog grupnog treninga:</label>
                    <div class="col-sm-3">
                        <input class="form-control" type="number" placeholder="Unesite cenu jednog grupnog treninga" max="1000000" onchange="CenaJednogGrupnogEmpty()" id="CenaJednogGrupnog" min="10" name="cenajednoggrupnog" />
                    </div>
                    <label id="Status7" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Cena treninga sa personalnim trenerom:</label>
                    <div class="col-sm-3">
                        <input class="form-control" type="number" placeholder="Unesite cenu treninga sa PT" max="1000000" onchange="CenaJednogPTEmpty()" id="CenaJednogPT" min="10" name="cenajednogpt" />
                    </div>
                    <label id="Status8" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-4">
                        <input class="btn btn-primary" type="submit" id="dugme" value="Dodaj fitnes centar" />
                    </div>
                </div>
            </div>    
        </form>
    </body>
</html>

Web1Project/Views/VlasnikUlogovan/MojiFitnesCentri.cshtml
@{
    ViewBag.Title = "MojiFitnesCentri";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Moji fitnes centri</title>

    <script type="text/javascript">

        function DeleteJob() {
            if (confirm("Da li ste sigurni da zelite da obrisete ovaj Fitnes centar?")){
                return true;
            }else{
                return false;
            }   
        }
    </script>
</head>
<body>
    @if (ViewBag.AlertMessage != null)
    {
        <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.AlertMessage");
                };
        </script>
    }
    <h2 class="text-info">Fitnes centri korisnika @ViewBag.vlasnik.KorisnickoIme</h2>
    <table class="table table-striped" border="1">
        <thead class="thead-light">
            <tr bgcolor="lightgrey">
                <td align="center"><strong>Naziv</strong></td>
                <td align="center"><strong>Adresa</strong></td>
                <td align="center"><strong>Godina otvaranja</strong></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.sortiranaLista)
            {
                <tr>
                    <td align="center">@item.Naziv</td>
                    <td align="center">@item.Adresa</td>
                    <td align="center">@item.GodinaOtvaranja</td>
                    <td align="center">
                        <form method="post" action="~/Home/Detalji?id=@item.Id">
                            <input class="btn btn-info" type="submit" value="Detalji" />
                        </form>
                    </td>
                    <td align="center">
                        <form method="post" action="~/VlasnikUlogovan/Izmeni?id=@item.Id">
                            <input class="btn btn-warning" type="submit" value="Izmeni fitnes centar" />
                        </form>
                    </td>
                    <td align="center">
                        <form method="post" onsubmit="return DeleteJob()" action="~/VlasnikUlogovan/ObrisiFitnesCentar?id=@item.Id">
                            <input class="btn btn-danger" type="submit" value="Obrisi fitnes centar" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <a class="btn btn-success" href="/VlasnikUlogovan/DodajFitnesCentar">Dodaj novi fitnes centar</a>
</body>
</html>

Web1Project/Views/VlasnikUlogovan/MojiTreneri.cshtml
@{
    ViewBag.Title = "MojiTreneri";
}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Moji zaposleni</title>
        <script>
            function DeleteJob() {
                if (confirm("Da li ste sigurni da zelite da blokirate ovog trenera?")){
                    return true;
                }else{
                    return false;
                }
            }
        </script>
    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.AlertMessage");
                };
            </script>
        }
        @if (ViewBag.treneri.Count != 0)
        {
            <h2 class="text-info">Treneri zaposleni u Vasim fitnes centrima</h2>
            <table class="table table-striped" border="1">
                <thead class="thead-light">
                    <tr bgcolor="lightgrey">
                        <td align="center"><strong>Korisnicko ime</strong></td>
                        <td align="center"><strong>Ime i prezime</strong></td>
                        <td align="center"><strong>Fitnes centar</strong></td>
                        <td>&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.treneri)
                    {
                        <tr>
                            <td align="center">@item.KorisnickoIme</td>
                            <td align="center">@item.Ime @item.Prezime</td>
                            <td align="center">@item.FitnesCentarZaposlen.Naziv</td>
                            <td align="center">
                                <form method="post" onsubmit="return DeleteJob()" action="~/VlasnikUlogovan/Blokiraj?id=@item.Id">
                                    <input class="btn btn-danger" type="submit" value="Blokiraj trenera" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h2>U vasim fitnes centrima nema zaposlenih</h2>
        }
        <br />
        <a class="btn btn-success" href="/VlasnikUlogovan/DodajTrenera">Registruj novog trenera</a>
    </body>
</html>