Web1Project/Controllers/AuthenticationController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Web1Project.Models;

namespace Web1Project.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            ViewBag.Ime = "";
            ViewBag.Message = "";

            Korisnik korisnik = new Korisnik();
            if ((Korisnik)Session["PrijavljeniKorisnik"] != null)
            {
                korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            }
            ViewBag.korisnik = korisnik;


            return View();
        }

        [HttpPost]
        public ActionResult Login(string korisnickoIme, string lozinka)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBase();

            if (korisnickoIme == "" || korisnickoIme == null || lozinka == "" || lozinka == null)
            {
                Session["AlertMessage"] = "Sva polja moraju biti popunjena";
                ViewBag.korisnik = new Korisnik();
                return View("Index");
            }

            lozinka = Operations.hashPassword(lozinka);

            if (korisnici.ContainsKey(korisnickoIme))
            {
                if(korisnici[korisnickoIme].Lozinka != lozinka)
                {
                    ViewBag.Ime = korisnickoIme;
                    ViewBag.korisnik = new Korisnik();

                    ViewBag.Message = "Pogresna lozinka";
                    return View("Index");
                }
            }
            else
            {
                Session["AlertMessage"] = "Ovo korisnicko ime ne postoji";
                ViewBag.korisnik = new Korisnik();
                return View("Index");
            }

            korisnici[korisnickoIme].LogIn();   
            Session["PrijavljeniKorisnik"] = korisnici[korisnickoIme];

            Session["AlertMessage"] = "Korisnik: " + korisnickoIme + " uspesno ulogovan!";
            return RedirectToAction("Index","Home");
        }

        public ActionResult Logout()
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];

            korisnici[korisnik.KorisnickoIme].LogOut();
            Session["PrijavljeniKorisnik"] = new Korisnik();

            if ((string)Session["AlertMessage"] != "Blokirani ste iz sistema!")
            {
                Session["AlertMessage"] = "Uspesno ste se odjavili!";
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public JsonResult CheckUserAvailability(string userdata)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBase();

            if (korisnici.ContainsKey(userdata))
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }
    }
}

Web1Project/Views/Authentication/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Log In</title>

    <script>

            var username = true;

            function UserNameCheck() {
                if ($("#korisnickoIme").val() == "") {

                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#korisnickoIme").css("border-color", "Red");

                }else{
                    $.post("@Url.Action("CheckUserAvailability", "Authentication")",
                    {
                        userdata: $("#korisnickoIme").val()
                    },
                    function (data) {
                        if (data == 0) {

                            $("#Status1").html('<font color="Red">Ovo korisnicko ime ne postoji!</font>');
                            $("#korisnickoIme").css("border-color", "Red");
                            username = false;
                        } else {

                            $("#Status1").html('');
                            $("#korisnickoIme").css("border-color", "lightgray");
                            username = true;
                        }
                    });
                }
            }

            function PasswordCheck() {
                if ($("#lozinka").val() == "") {

                    $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#lozinka").css("border-color", "Red");

                } else {
                    $("#Status2").html('');
                    $("#lozinka").css("border-color", "lightgray");
                }
            }


            function validateForm() {

                var dobro = true;

                if ($("#korisnickoIme").val() == "") {
                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#korisnickoIme").css("border-color", "Red");
                    dobro = false;
                } else if (username){
                    $("#Status1").html('');
                    $("#korisnickoIme").css("border-color", "lightgray");
                }
                if ($("#lozinka").val() == "") {
                    $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#lozinka").css("border-color", "Red");
                    dobro = false;
                } else {
                    $("#Status2").html('');
                    $("#lozinka").css("border-color", "lightgray");
                }

                return (dobro && username);
            }
    </script>

    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
</head>
    <body>
        <h2 class="text-info">Ulogujte se:</h2>
        <br/>
        <form method="post" action="~/Authentication/Login" onsubmit="return validateForm()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Korisnicko ime:</label>
                    <div class="col-sm-3">
                        <input class="form-control" type="text" value="@ViewBag.Ime" onchange="UserNameCheck()" maxlength="30" placeholder="Unesite korisnicko ime" id="korisnickoIme" name="korisnickoIme" />
                    </div>
                    <label class="col-sm-4" id="Status1"></label>
                </div>
                <br/>
                <div class="row">
                    <label class="control-label col-sm-2">Lozinka:</label>
                    <div class="col-sm-3">
                        <input class="form-control" type="password" onchange="PasswordCheck()" maxlength="30" placeholder="Unesite lozinku" id="lozinka" name="lozinka" />
                    </div>
                    <label class="col-sm-4" id="Status2"><font color="Red">@ViewBag.Message</font></label>
                </div>
                <br/>
                <div class="row">
                    <div class="col-sm-4">
                        <input class="btn btn-primary" type="submit" value="Uloguj se" />
                    </div>
                </div>
            </div>
        </form>
        <br />
    </body>
</html>