Web1Project/Controllers/MojNalogController.cs
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Xml;
using Web1Project.Models;

namespace Web1Project.Controllers
{
    public class MojNalogController : Controller
    {
        // GET: MojNalog
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if(korisnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            if (!korisnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            if (korisnik.Uloga == Uloga.TRENER)
            {
                if (Load.KorisnikBlokiran(korisnik.Id))
                {
                    Session["AlertMessage"] = "Blokirani ste iz sistema!";
                    return RedirectToAction("Logout", "Authentication");
                }
            }

            ViewBag.korisnik = korisnik;

            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }
            else
            {
                ViewBag.AlertMessage = null;
            }

            return View();
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult LicniPodaci()
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (korisnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            if (!korisnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            if (korisnik.Uloga == Uloga.TRENER)
            {
                if (Load.KorisnikBlokiran(korisnik.Id))
                {
                    Session["AlertMessage"] = "Blokirani ste iz sistema!";
                    return RedirectToAction("Logout", "Authentication");
                }
            }



            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }
            else
            {
                ViewBag.AlertMessage = null;
            }

            ViewBag.korisnik = korisnik;

            return View();
        }

        [HttpPost]
        public ActionResult LicniPodaciPromenjeni(string korisnickoime, string ime, string prezime)
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();

            bool flag = false;

            if (korisnickoime != "" || ime != "" || prezime != "")
            {
                XmlDocument xmlDoc = new XmlDocument();
                string path = Path.Combine(Server.MapPath("~/App_Data/korisnici.xml"));
                xmlDoc.Load(path);
                XmlNodeList nodeList = xmlDoc.DocumentElement.SelectNodes($"/Korisnici/Korisnik");

                if (ime != "" && ime != korisnik.Ime)
                {
                    foreach (XmlNode node in nodeList)
                    {
                        if (node.SelectSingleNode("KorisnickoIme").InnerText == korisnik.KorisnickoIme)
                        {
                            flag = true;
                            node.SelectSingleNode("Ime").InnerText = ime;

                            korisnik.Ime = ime;
                            break;
                        }
                    }
                }
                if (prezime != "" && prezime!=korisnik.Prezime)
                {
                    foreach (XmlNode node in nodeList)
                    {
                        if (node.SelectSingleNode("KorisnickoIme").InnerText == korisnik.KorisnickoIme)
                        {
                            flag = true;
                            node.SelectSingleNode("Prezime").InnerText = prezime;

                            korisnik.Prezime = prezime;
                            break;
                        }
                    }
                }

                if (korisnickoime != "" && korisnickoime!=korisnik.KorisnickoIme)
                {
                    if (korisnici.ContainsKey(korisnickoime))
                    {
                        Session["AlertMessage"] = "Ovo korisnicko ime je zauzeto!";
                        return RedirectToAction("LicniPodaci");
                    }
                    else
                    {
                        foreach (XmlNode node in nodeList)
                        {
                            if (node.SelectSingleNode("KorisnickoIme").InnerText == korisnik.KorisnickoIme)
                            {
                                flag = true;
                                node.SelectSingleNode("KorisnickoIme").InnerText = korisnickoime;

                                korisnik.KorisnickoIme = korisnickoime;
                                break;
                            }
                        }
                    }
                }

                if (flag)
                {
                    xmlDoc.Save(path);  
                    Session["AlertMessage"] = "Licni podaci uspesno izmenjeni!";

                    Session["PrijavljeniKorisnik"] = korisnik;
                }
                else
                {
                    Session["AlertMessage"] = "Licni podaci nisu izmenjeni!";
                }            
            }          
            return RedirectToAction("Index");
        }
        
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Email()
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (korisnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if (!korisnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            if (korisnik.Uloga == Uloga.TRENER)
            {
                if (Load.KorisnikBlokiran(korisnik.Id))
                {
                    Session["AlertMessage"] = "Blokirani ste iz sistema!";
                    return RedirectToAction("Logout", "Authentication");
                }
            }

            ViewBag.Message1 = "";
            ViewBag.Message2 = "";
            ViewBag.korisnik = korisnik;

            return View();
        }

        [HttpPost]
        public ActionResult EmailPromenjen(string email, string lozinka)
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];

            if (email != "" && email != korisnik.Email)
            {
                bool isEmail = Regex.IsMatch(email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

                lozinka = Operations.hashPassword(lozinka);

                if (lozinka == korisnik.Lozinka && isEmail)
                {
                    XmlDocument xmlDoc = new XmlDocument();
                    string path = Path.Combine(Server.MapPath("~/App_Data/korisnici.xml"));
                    xmlDoc.Load(path);
                    XmlNodeList nodeList = xmlDoc.DocumentElement.SelectNodes($"/Korisnici/Korisnik");

                    foreach (XmlNode node in nodeList)
                    {
                        if (node.SelectSingleNode("KorisnickoIme").InnerText == korisnik.KorisnickoIme)
                        {
                            node.SelectSingleNode("Email").InnerText = email;

                            korisnik.Email = email;

                            xmlDoc.Save(path);
                            Session["PrijavljeniKorisnik"] = korisnik;
                            break;
                        }
                    }
                    Session["AlertMessage"] = "Email uspesno izmenjen!"; 
                }
                else
                {
                    if (!isEmail)
                    {
                        ViewBag.Message1 = "Email nije validan";
                    }

                    if (lozinka != korisnik.Lozinka)
                    {
                        ViewBag.Message2 = "Neispravna lozinka";
                    }

                    ViewBag.korisnik = korisnik;
                    return View("Email");
                }
            }
            ViewBag.korisnik = korisnik;
            return RedirectToAction("Index");
        }
      
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Lozinka()
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            if (korisnik == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if (!korisnik.LogedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            if (korisnik.Uloga == Uloga.TRENER)
            {
                if (Load.KorisnikBlokiran(korisnik.Id))
                {
                    Session["AlertMessage"] = "Blokirani ste iz sistema!";
                    return RedirectToAction("Logout", "Authentication");
                }
            }

            ViewBag.Message1 = "";
            ViewBag.Message2 = "";

            ViewBag.korisnik = korisnik;

            return View();
        }

        [HttpPost]
        public ActionResult LozinkaPromenjena(string lozinka, string novalozinka, string novalozinkaponovo)
        {
            Korisnik korisnik = (Korisnik)Session["PrijavljeniKorisnik"];

Web1Project/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Web1Project.Models;

namespace Web1Project.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult Index()
        {
            if (Session["AlertMessage"] != null)
            {
                ViewBag.AlertMessage = Session["AlertMessage"];
                Session["AlertMessage"] = null;
            }

            Korisnik korisnik = new Korisnik();
            if ((Korisnik)Session["PrijavljeniKorisnik"] != null)
            {
                korisnik = (Korisnik)Session["PrijavljeniKorisnik"];
            }
            ViewBag.korisnik = korisnik;

            return View();
        }

        [HttpPost]
        public JsonResult CheckUserAvailability(string userdata)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();

            if (korisnici.ContainsKey(userdata))
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult EmailValidation(string email)
        {
            bool isEmail = Regex.IsMatch(email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

            if (isEmail)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        [HttpPost]
        public ActionResult Add(Korisnik korisnik)
        {
            Dictionary<string, Korisnik> korisnici = Load.KorisnikFromDataBaseObrisani();

            if (korisnik.KorisnickoIme == null || korisnik.KorisnickoIme == "" || korisnik.Ime == null || korisnik.Ime == "" || korisnik.Prezime == null || korisnik.Prezime == "" || korisnik.Lozinka == null || korisnik.Lozinka == "" || korisnik.Email == null || korisnik.Email == "" || korisnik.DatumRodjenja > DateTime.Now)
            {
                Session["AlertMessage"] = "Sva polja moraju biti popunjena";
                return RedirectToAction("Index");
            }

            if (korisnici.ContainsKey(korisnik.KorisnickoIme))
            {
                Session["AlertMessage"] = "Korisnicko ime je zauzeto";
                return RedirectToAction("Index");
            }

            bool isEmail = Regex.IsMatch(korisnik.Email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

            if (isEmail)
            {
                korisnik.Id = korisnici.Count;
                korisnik.PosecujeGrupneTreninge = new List<GrupniTrening>();

                korisnik.Lozinka = Operations.hashPassword(korisnik.Lozinka);

                Write.PosetilacToDataBase(korisnik);

                Session["AlertMessage"] = "Korisnik uspesno registrovan!";                
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Session["AlertMessage"] = "Email nije validan";
                return RedirectToAction("Index");
            }
        }
    }
}

Web1Project/Views/MojNalog/Email.cshtml
@{
    ViewBag.Title = "Email";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>E-mail</title>

    <script>

        function emailEmpty() {
            if ($("#email").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#email").css("border-color", "Red");
            } else {
                $.post("@Url.Action("EmailValidation", "Registration")",
                {
                    email: $("#email").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#Status1").html('<font color="Red">Email nije validan!</font>');
                        $("#email").css("border-color", "Red");
                        email = false;
                    } else {
                        $("#Status1").html('');
                        $("#email").css("border-color", "lightgray");
                        email = true;
                    }
                });
            }
        }

        function lozinkaEmpty() {
            if ($("#lozinka").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#lozinka").css("border-color", "Red");
            } else {
                $("#Status2").html('');
                $("#lozinka").css("border-color", "lightgray");
            }
        }

        function validateForm() {
            var dobro = true;

            if ($("#email").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#email").css("border-color", "Red");
                dobro = false;
            } else if(email){
                $("#Status1").html('');
                $("#email").css("border-color", "lightgray");
            }

            if ($("#lozinka").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#lozinka").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status2").html('');
                $("#lozinka").css("border-color", "lightgray");
            }

            return (dobro && email);
        }
    </script>

    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>

</head>
    <body>
        <br /><br />
        <table>
            <tr>
                <td><strong>Trenutna e-mail adresa</strong></td>
            </tr>
            <tr>
                <td align="center">@ViewBag.korisnik.Email</td>
            </tr>
        </table>
        <br /><br />
        <form method="post" action="~/MojNalog/EmailPromenjen" onsubmit="return validateForm()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Nova e-mail adresa</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite novu e-mail adresu" onchange="emailEmpty()" type="email" maxlength="40" id="email" name="email" />
                    </div>
                    <label id="Status1" class="control-label col-sm-4"><font color="Red">@ViewBag.Message1</font></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Vazeca lozinka</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite vazecu lozinku" onchange="lozinkaEmpty()" type="password" id="lozinka" name="lozinka" />
                    </div>
                    <label id="Status2" class="control-label col-sm-4"><font color="Red">@ViewBag.Message2</font></label>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-3">
                        <input class="btn btn-primary" type="submit" value="Sacuvaj izmene" />
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

Web1Project/Views/MojNalog/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Moj Nalog</title>
    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.AlertMessage");
                };
            </script>
        }
        <h2>Licni podaci</h2>

        <br />

        <h4><a href="~/MojNalog/LicniPodaci">Promena licnih podataka</a></h4>
        <h5>@ViewBag.korisnik.KorisnickoIme, @ViewBag.korisnik.Ime @ViewBag.korisnik.Prezime</h5> <br />

        <h4><a href="~/MojNalog/Lozinka">Promena lozinke</a></h4> <br />

        <h4><a href="~/MojNalog/Email">Promena E-mail adrese</a></h4>
        <h5>@ViewBag.korisnik.Email</h5>

    </body>
</html>

Web1Project/Views/MojNalog/LicniPodaci.cshtml
@{
    ViewBag.Title = "LicniPodaci";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Licni Podaci</title>

    <script>

        var username = true;

        function UserCheck() {

            if ($("#KorisnickoIme").val() != "") {
                $.post("@Url.Action("CheckUserAvailability", "Registration")",
                {
                    userdata: $("#KorisnickoIme").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#Status1").html('<font color="Green">Korisnicko ime je slobodno!</font>');
                        $("#KorisnickoIme").css("border-color", "GreenYellow");
                        username = true;
                    } else {
                        $("#Status1").html('<font color="Red">Ovo korisnicko ime je zauzeto!</font>');
                        $("#KorisnickoIme").css("border-color", "Red");
                        username = false;
                    }
                });
            } 
        }

        function validateForm() {
            return username;
        }

    </script>

    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
</head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.AlertMessage");
                };
            </script>
        }
        <br /><br />
        <table>
            <tr>
                <td><strong>Trenutno korisnicko ime</strong></td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td><strong>Trenutno ime i prezime</strong></td>
            </tr>
            <tr>
                <td align="center">@ViewBag.korisnik.KorisnickoIme</td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td align="center">@ViewBag.korisnik.Ime  @ViewBag.korisnik.Prezime</td>
            </tr>
        </table> 
        <br/><br/>
        
        <form method="post" action="~/MojNalog/LicniPodaciPromenjeni" onsubmit="return validateForm()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Novo korisnicko ime</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" type="text" placeholder="Unesite novo korisnicko ime" maxlength="30" id="KorisnickoIme" name="korisnickoime" onchange="UserCheck()" />
                    </div>
                    <label class="control-label col-sm-4" id="Status1"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Novo ime</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" type="text" placeholder="Unesite novo ime" maxlength="20" name="ime" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Novo prezime</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" type="text" placeholder="Unesite novo prezime" maxlength="30" name="prezime" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-3">
                        <input class="btn btn-primary" type="submit" value="Sacuvaj izmene" />
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

Web1Project/Views/MojNalog/Lozinka.cshtml
@{
    ViewBag.Title = "Lozinka";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <script>

        function StaraLozinkaEmpty() {
            if ($("#lozinka").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#lozinka").css("border-color", "Red");
            } else {
                $("#Status1").html('');
                $("#lozinka").css("border-color", "lightgray");
            }
        }

        function NovaLozinkaEmpty() {
            if ($("#novalozinka").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#novalozinka").css("border-color", "Red");
            } else {
                $("#Status2").html('');
                $("#novalozinka").css("border-color", "lightgray");
            }
        }

        function PonovljenaEmpty() {
            if ($("#novalozinkaponovo").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#novalozinkaponovo").css("border-color", "Red");
            } else {
                $("#Status3").html('');
                $("#novalozinkaponovo").css("border-color", "lightgray");
            }
        }

        function validateForm() {
            var dobro = true;

            if ($("#lozinka").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#lozinka").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status1").html('');
                $("#lozinka").css("border-color", "lightgray");
            }

            if ($("#novalozinka").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#novalozinka").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status2").html('');
                $("#novalozinka").css("border-color", "lightgray");
            }

            if ($("#novalozinkaponovo").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#novalozinkaponovo").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status3").html('');
                $("#novalozinkaponovo").css("border-color", "lightgray");
            }

            return dobro;
        }

    </script>

    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>

</head>
    <body>
        <br/><br/>
        <form method="post" action="~/MojNalog/LozinkaPromenjena" onsubmit="return validateForm()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Vezeca lozinka</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite vazecu lozinku" onchange="StaraLozinkaEmpty()" type="password" id="lozinka" name="lozinka" />
                    </div>
                    <label id="Status1" class="control-label col-sm-4"><font color="Red">@ViewBag.Message1</font></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Nova lozinka</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite novu lozinku" onchange="NovaLozinkaEmpty()" type="password" id="novalozinka" name="novalozinka" />
                    </div>
                    <label id="Status2" class="control-label col-sm-4"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Ponovite novu lozinku</label>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Ponovo unesite lozinku" onchange="PonovljenaEmpty()" type="password" id="novalozinkaponovo" name="novalozinkaponovo" />
                    </div>
                    <label id="Status3" class="control-label col-sm-4"><font color="Red">@ViewBag.Message2</font></label>
                </div>
                <br />
                <div class="row">
                    <div class="col-sm-3">
                        <input class="btn btn-primary" type="submit" value="Sacuvaj izmene" />
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>